import React, { createContext, useContext, useState, useEffect } from 'react';

export const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' }
];

const TRANSLATIONS = {
  en: {
    brand_tagline: 'Smart Land Governance Platform',
    active_workspace: 'Active Workspace',
    citizen_portal: 'Citizen Portal',
    administration: 'Administration',
    dept_operations: 'Department Operations',
    cadastral_inspections: 'Cadastral Inspections',
    cadastral_tools: 'Cadastral Tools',
    dashboard: 'Citizen Dashboard',
    my_applications: 'My Applications',
    apply_services: 'Apply for Services',
    cadastral_map: 'Cadastral GIS Map',
    services: 'Government Services',
    profile: 'Profile & Security',
    logout: 'Sign Out',
    verified_portal: 'Verified Citizen Portal',
    greeting: 'Namaste',
    welcome_msg: 'Welcome to your integrated LandStack workspace. Inspect cadastral records, submit online service applications, and track departmental verifications in real-time.',
    apply_for_service: 'Apply for Service',
    view_records: 'View Records',
    quick_search: 'Quick Search:',
    search_cadastre: 'Search Cadastre Records',
    universal_search_title: 'Universal Cadastral Parcel Lookup — 10 Statutory Departments',
    universal_search_desc: 'Search any land parcel by ULPIN (Bhu-Aadhaar), Survey Number, or Aadhaar Number to inspect unified records across all 10 statutory departments.',
    enter_search_placeholder: 'Enter 14-digit ULPIN, Survey Number (e.g. 124/3B), or Masked Aadhaar (e.g. 4819)...',
    all_10_departments: '10 Statutory Departments',
    unified_records_title: '10-Department Unified Card Records',
    hide_records: 'Hide Records',
    show_records: 'Show Records',
    statutory_records_title: 'Statutory Department Records',
    statutory_records_desc: 'Select any department card below to pop up and inspect its comprehensive verified parameters.',
    view_details: 'View Details',
    parameters: 'Parameters',
    dept_prefix: 'Dept',
    bhu_aadhaar_ulpin: 'Bhu-Aadhaar ULPIN',
    integrated_cadastre_subtitle: '10 Statutory Departments Integrated Cadastre',
    ulpin_label: 'ULPIN',
    survey_label: 'Survey No',
    owner_label: 'Owner',
    aadhaar_label: 'Aadhaar',
    owner_name: 'Owner Name',
    masked_aadhaar: 'Masked Aadhaar',
    survey_subdiv: 'Survey / Sub-Division',
    location: 'Location',
    inspect_map: 'Inspect on GIS Map',
    print_records: 'Print Records',
    verified_footnote: 'Verified against National Cadastral Repository & Statutory Portals.',
    press_esc_close: 'Press ✕ above to close',
    my_applications_title: 'My Service Applications',
    my_applications_desc: 'Live statutory application lifecycle tracking',
    view_all: 'View All',
    col_app_number: 'App Number',
    col_service: 'Service',
    col_ulpin: 'Parcel ULPIN',
    col_dept: 'Department',
    col_status: 'Status',
    col_applied_date: 'Applied Date',
    col_action: 'Action',
    track_action: 'Track',
    ai_assistant: 'LandStack AI Assistant',
    ask_ai: 'Ask LandStack AI',
    online: 'Online',
    offline: 'Offline',
    syncing: 'Syncing',
    select_language: 'Change Language',
    role_citizen: 'CITIZEN',
    role_supervisor: 'SUPERVISOR',
    role_field_officer: 'FIELD OFFICER',
    role_admin: 'ADMIN',
    notifications: 'Notifications',
    mark_all_read: 'Mark all read',
    no_notifications: 'No new notifications',
    signed_in_as: 'Signed in as',
    agriculture_section: 'Agriculture Section',
    agriculture_section_sub: 'Cropping patterns, irrigation sources and soil taxonomy',
    forest_section: 'Forest Section',
    forest_section_sub: 'Forest boundaries, buffer zones and eco-sensitive conservation',
    ai_sahayak: 'AI Sahayak',
    ai_subtitle: 'Statutory Services & Cadastral Knowledge',
    ai_input_placeholder: 'Ask about Patta, ULPIN, EC, or Services...',
    ai_listening: 'Listening to speech... Speak your query clearly',
    ai_disclaimer: 'Specialized exclusively in LandStack statutory services and Indian land records.',
    status_submitted: 'Submitted',
    status_under_review: 'Under Review',
    status_pending_documents: 'Pending Docs',
    status_field_verification: 'Field Inspection',
    status_verified: 'Site Verified',
    status_supervisor_review: 'Final Review',
    status_approved: 'Approved',
    status_completed: 'Completed',
    status_rejected: 'Rejected',

    // 10 Departments
    dept_1_title: 'Revenue Department',
    dept_1_sub: 'Land Administration, Patta Registers & Jamabandi Records',
    dept_2_title: 'Survey & Land Records Department',
    dept_2_sub: 'Cadastral GIS Map, FMB Sketch & Spatial Boundaries',
    dept_3_title: 'Registration Department',
    dept_3_sub: 'Registered Transactions, Encumbrance (EC) & Title Deeds',
    dept_4_title: 'Local Bodies',
    dept_4_sub: 'Panchayat / Municipality Property Tax & Assessment',
    dept_5_title: 'Public Works Department — PWD',
    dept_5_sub: 'Roads, Canals, ROW Alignment & Infrastructure Expansion',
    dept_6_title: 'Municipal Administration',
    dept_6_sub: 'Urban Properties, Building Permissions & Utility Services',
    dept_7_title: 'Agriculture & Forest Department',
    dept_7_sub: 'Soil/Crop Classification & Protected Forest Buffer Zones',
    dept_8_title: 'Electricity Department',
    dept_8_sub: 'TANGEDCO / Grid Utilities, HT Corridors & Transformers',
    dept_9_title: 'Environment-Related Authorities',
    dept_9_sub: 'CRZ, Wetlands, Flood Plains & Eco-Sensitive Clearances',
    dept_10_title: 'Local Planning / Town & Country Planning',
    dept_10_sub: 'Master Plan Zoning, FSI/FAR, Setbacks & Permissions'
  },
  ta: {
    brand_tagline: 'ஸ்மார்ட் நில ஆளுகை தளம்',
    active_workspace: 'செயலில் உள்ள பணியிடம்',
    citizen_portal: 'குடிமக்கள் போர்டல்',
    administration: 'நிர்வாகம்',
    dept_operations: 'துறை செயல்பாடுகள்',
    cadastral_inspections: 'நில அளவை ஆய்வுகள்',
    cadastral_tools: 'நில அளவைக் கருவிகள்',
    dashboard: 'குடிமக்கள் முகப்பு பலகை',
    my_applications: 'எனது விண்ணப்பங்கள்',
    apply_services: 'சேவைகளுக்கு விண்ணப்பிக்கவும்',
    cadastral_map: 'நில அளவை ஜிஐஎஸ் வரைபடம்',
    services: 'அரசு சேவைகள்',
    profile: 'சுயவிவரம் & பாதுகாப்பு',
    logout: 'வெளியேறு',
    verified_portal: 'சரிபார்க்கப்பட்ட குடிமக்கள் போர்டல்',
    greeting: 'வணக்கம்',
    welcome_msg: 'ஒருங்கிணைந்த லேண்ட்ஸ்டாக் பணியிடத்திற்கு வரவேற்கிறோம். நில ஆவணங்களைச் சரிபார்க்கவும், ஆன்லைன் சேவைகளுக்கு விண்ணப்பிக்கவும், துறைசார் சரிபார்ப்புகளை கண்காணிக்கவும்.',
    apply_for_service: 'சேவைக்கு விண்ணப்பிக்க',
    view_records: 'பதிவுகளை காண்க',
    quick_search: 'விரைவு தேடல்:',
    search_cadastre: 'நில பதிவுகளை தேடுங்கள்',
    universal_search_title: 'ஒருங்கிணைந்த நில பார்சல் தேடல் — 10 சட்டப்பூர்வ துறைகள்',
    universal_search_desc: 'அனைத்து 10 சட்டப்பூர்வ துறைகளிலும் நில பதிவுகளை சரிபார்க்க ULPIN (பூ-ஆதார்), சர்வே எண் அல்லது ஆதார் எண் மூலம் தேடுங்கள்.',
    enter_search_placeholder: '14 இலக்க ULPIN, சர்வே எண் (எ.கா. 124/3B), அல்லது ஆதார் எண் உள்ளிடவும்...',
    all_10_departments: '10 சட்டப்பூர்வ துறைகள்',
    unified_records_title: '10 துறைகளின் ஒருங்கிணைந்த அட்டை பதிவுகள்',
    hide_records: 'பதிவுகளை மறைக்க',
    show_records: 'பதிவுகளைக் காட்டுக',
    statutory_records_title: 'சட்டப்பூர்வ துறை பதிவுகள்',
    statutory_records_desc: 'விரிவான சரிபார்க்கப்பட்ட அளவுருக்களைப் பார்வையிட கீழே உள்ள ஏதேனும் துறை அட்டையைத் தேர்ந்தெடுக்கவும்.',
    view_details: 'விவரங்களை காண்க',
    parameters: 'அளவுருக்கள்',
    dept_prefix: 'துறை',
    bhu_aadhaar_ulpin: 'பூ-ஆதார் ULPIN',
    integrated_cadastre_subtitle: '10 சட்டப்பூர்வ துறைகள் ஒருங்கிணைந்த நில அளவை',
    ulpin_label: 'ULPIN',
    survey_label: 'சர்வே எண்',
    owner_label: 'உரிமையாளர்',
    aadhaar_label: 'ஆதார்',
    owner_name: 'உரிமையாளர் பெயர்',
    masked_aadhaar: 'மறைக்கப்பட்ட ஆதார்',
    survey_subdiv: 'சர்வே / உட்பிரிவு',
    location: 'இடம்',
    inspect_map: 'வரைபடத்தில் காண்க',
    print_records: 'அச்சிடுக',
    verified_footnote: 'தேசிய நில அளவை களஞ்சியம் மற்றும் சட்டப்பூர்வ போர்ட்டல்கள் மூலம் சரிபார்க்கப்பட்டது.',
    press_esc_close: 'மூட மேலே உள்ள ✕-ஐ அழுத்தவும்',
    my_applications_title: 'எனது சேவை விண்ணப்பங்கள்',
    my_applications_desc: 'நேரலை சட்டப்பூர்வ விண்ணப்ப வாழ்க்கை சுழற்சி கண்காணிப்பு',
    view_all: 'அனைத்தையும் காண்க',
    col_app_number: 'விண்ணப்ப எண்',
    col_service: 'சேவை',
    col_ulpin: 'பார்சல் ULPIN',
    col_dept: 'துறை',
    col_status: 'நிலை',
    col_applied_date: 'விண்ணப்பித்த தேதி',
    col_action: 'செயல்',
    track_action: 'கண்காணி',
    ai_assistant: 'லேண்ட்ஸ்டாக் ஏஐ உதவியாளர்',
    ask_ai: 'ஏஐ உதவியாளரிடம் கேளுங்கள்',
    online: 'இணையத்தில்',
    offline: 'ஆஃப்லைன்',
    syncing: 'ஒத்திசைக்கப்படுகிறது',
    select_language: 'மொழியை மாற்றுக',
    role_citizen: 'குடிமகன்',
    role_supervisor: 'மேற்பார்வையாளர்',
    role_field_officer: 'கள அதிகாரி',
    role_admin: 'நிர்வாகி',
    notifications: 'அறிவிப்புகள்',
    mark_all_read: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    no_notifications: 'புதிய அறிவிப்புகள் இல்லை',
    signed_in_as: 'உள்நுழைந்துள்ள கணக்கு',
    agriculture_section: 'வேளாண்மை பிரிவு',
    agriculture_section_sub: 'பயிர் முறைகள், பாசன ஆதாரங்கள் மற்றும் மண் வகைப்பாடு',
    forest_section: 'வனத்துறை பிரிவு',
    forest_section_sub: 'வன எல்லைகள், இடையக மண்டலங்கள் மற்றும் சூழல் பாதுகாப்பு',
    ai_sahayak: 'ஏஐ உதவியாளர்',
    ai_subtitle: 'சட்டப்பூர்வ சேவைகள் & நில அளவை அறிவு',
    ai_input_placeholder: 'பட்டா, ULPIN, EC அல்லது சேவைகள் பற்றி கேளுங்கள்...',
    ai_listening: 'பேச்சைக் கேட்கிறது... உங்கள் கேள்வியை தெளிவாகக் கூறுங்கள்',
    ai_disclaimer: 'லேண்ட்ஸ்டாக் சட்டப்பூர்வ சேவைகள் மற்றும் இந்திய நில ஆவணங்களில் பிரத்யேகமானது.',
    status_submitted: 'சமர்ப்பிக்கப்பட்டது',
    status_under_review: 'பரிசீலனையில்',
    status_pending_documents: 'ஆவணங்கள் நிலுவையில்',
    status_field_verification: 'கள ஆய்வு',
    status_verified: 'சரிபார்க்கப்பட்டது',
    status_supervisor_review: 'இறுதி மதிப்பாய்வு',
    status_approved: 'அங்கீகரிக்கப்பட்டது',
    status_completed: 'நிறைவடைந்தது',
    status_rejected: 'நிராகரிக்கப்பட்டது',

    // 10 Departments
    dept_1_title: 'வருவாய்த்துறை',
    dept_1_sub: 'நில நிர்வாகம், பட்டா பதிவேடுகள் மற்றும் ஜமாபந்தி பதிவுகள்',
    dept_2_title: 'நில அளவை மற்றும் நில பதிவேடுகள் துறை',
    dept_2_sub: 'நில வரைபடம், FMB வரைபடம் மற்றும் எல்லைகள்',
    dept_3_title: 'பதிவுத்துறை',
    dept_3_sub: 'பதிவு செய்யப்பட்ட பரிவர்த்தனைகள், வில்லங்கச் சான்றிதழ் (EC) மற்றும் பத்திரங்கள்',
    dept_4_title: 'உள்ளாட்சி அமைப்புகள்',
    dept_4_sub: 'ஊராட்சி / நகராட்சி சொத்து வரி மற்றும் மதிப்பீடு',
    dept_5_title: 'பொதுப்பணித்துறை (PWD)',
    dept_5_sub: 'சாலைகள், கால்வாய்கள், ROW சீரமைப்பு மற்றும் உள்கட்டமைப்பு',
    dept_6_title: 'நகராட்சி நிர்வாகம்',
    dept_6_sub: 'நகர சொத்துக்கள், கட்டிட அனுமதிகள் மற்றும் பயன்பாட்டு சேவைகள்',
    dept_7_title: 'வேளாண்மை மற்றும் வனத்துறை',
    dept_7_sub: 'மண்/பயிர் வகைப்பாடு மற்றும் பாதுகாக்கப்பட்ட வன மண்டலங்கள்',
    dept_8_title: 'மின்சாரத்துறை',
    dept_8_sub: 'மின்சார பயன்பாடுகள், மின்கம்பங்கள் மற்றும் மின்மாற்றிகள்',
    dept_9_title: 'சுற்றுச்சூழல் அதிகார அமைப்புகள்',
    dept_9_sub: 'CRZ, ஈரநிலங்கள், வெள்ளச் சமவெளிகள் மற்றும் அனுமதிகள்',
    dept_10_title: 'நகர் மற்றும் ஊரமைப்புத் திட்டமிடல்',
    dept_10_sub: 'முக்கிய திட்ட மண்டலங்கள், FSI/FAR மற்றும் அனுமதிகள்'
  },
  hi: {
    brand_tagline: 'स्मार्ट भूमि शासन मंच',
    active_workspace: 'सक्रिय कार्यक्षेत्र',
    citizen_portal: 'नागरिक पोर्टल',
    administration: 'प्रशासन',
    dept_operations: 'विभागीय कार्य',
    cadastral_inspections: 'भू-कर निरीक्षण',
    cadastral_tools: 'भू-अभिलेख उपकरण',
    dashboard: 'नागरिक डैशबोर्ड',
    my_applications: 'मेरे आवेदन',
    apply_services: 'सेवाओं के लिए आवेदन करें',
    cadastral_map: 'भू-कर जीआईएस मानचित्र',
    services: 'सरकारी सेवाएं',
    profile: 'प्रोफ़ाइल एवं सुरक्षा',
    logout: 'लॉग आउट',
    verified_portal: 'सत्यापित नागरिक पोर्टल',
    greeting: 'नमस्ते',
    welcome_msg: 'एकीकृत लैंडस्टैक कार्यक्षेत्र में आपका स्वागत है। भू-अभिलेखों का निरीक्षण करें, ऑनलाइन सेवाओं के लिए आवेदन करें और स्थिति ट्रैक करें।',
    apply_for_service: 'सेवा के लिए आवेदन करें',
    view_records: 'अभिलेख देखें',
    quick_search: 'त्वरित खोज:',
    search_cadastre: 'भू-अभिलेख खोजें',
    universal_search_title: 'सार्वभौमिक भू-पार्सल खोज — 10 वैधानिक विभाग',
    universal_search_desc: 'सभी 10 वैधानिक विभागों में एकीकृत अभिलेखों का निरीक्षण करने के लिए यूलपिन (भू-आधार), सर्वेक्षण संख्या, या आधार संख्या द्वारा खोजें।',
    enter_search_placeholder: '14-अंकीय यूलपिन, सर्वेक्षण संख्या (उदा. 124/3B), या आधार (उदा. 4819) दर्ज करें...',
    all_10_departments: '10 वैधानिक विभाग',
    unified_records_title: '10 विभागों के एकीकृत कार्ड अभिलेख',
    hide_records: 'अभिलेख छुपाएं',
    show_records: 'अभिलेख दिखाएं',
    statutory_records_title: 'वैधानिक विभाग अभिलेख',
    statutory_records_desc: 'विस्तृत सत्यापित मापदंडों का निरीक्षण करने के लिए नीचे दिए गए किसी भी विभाग कार्ड पर क्लिक करें।',
    view_details: 'विवरण देखें',
    parameters: 'मापदंड',
    dept_prefix: 'विभाग',
    bhu_aadhaar_ulpin: 'भू-आधार यूलपिन',
    integrated_cadastre_subtitle: '10 वैधानिक विभागों का एकीकृत भू-कर',
    ulpin_label: 'यूलपिन',
    survey_label: 'सर्वेक्षण सं.',
    owner_label: 'स्वामी',
    aadhaar_label: 'आधार',
    owner_name: 'स्वामी का नाम',
    masked_aadhaar: 'आधार संख्या',
    survey_subdiv: 'सर्वेक्षण / उप-प्रभाग',
    location: 'स्थान',
    inspect_map: 'मानचित्र पर देखें',
    print_records: 'प्रिंट अभिलेख',
    verified_footnote: 'राष्ट्रीय भू-कर भंडार और वैधानिक पोर्टलों द्वारा सत्यापित।',
    press_esc_close: 'बंद करने के लिए ऊपर ✕ दबाएं',
    my_applications_title: 'मेरे सेवा आवेदन',
    my_applications_desc: 'लाइव वैधानिक आवेदन जीवन चक्र ट्रैकिंग',
    view_all: 'सभी देखें',
    col_app_number: 'आवेदन संख्या',
    col_service: 'सेवा',
    col_ulpin: 'पार्सल यूलपिन',
    col_dept: 'विभाग',
    col_status: 'स्थिति',
    col_applied_date: 'आवेदन तिथि',
    col_action: 'कार्रवाई',
    track_action: 'ट्रैक करें',
    ai_assistant: 'लैंडस्टैक एआई सहायक',
    ask_ai: 'एआई सहायक से पूछें',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    syncing: 'सिंक हो रहा है',
    select_language: 'भाषा बदलें',
    role_citizen: 'नागरिक',
    role_supervisor: 'पर्यवेक्षक',
    role_field_officer: 'क्षेत्र अधिकारी',
    role_admin: 'प्रशासक',
    notifications: 'सूचनाएं',
    mark_all_read: 'सभी को पढ़ा हुआ चिह्नित करें',
    no_notifications: 'कोई नई सूचना नहीं है',
    signed_in_as: 'के रूप में साइन इन हैं',
    agriculture_section: 'कृषि अनुभाग',
    agriculture_section_sub: 'फसल पैटर्न, सिंचाई स्रोत और मिट्टी वर्गीकरण',
    forest_section: 'वन अनुभाग',
    forest_section_sub: 'वन सीमाएं, बफर जोन और पर्यावरण-संवेदनशील संरक्षण',
    ai_sahayak: 'एआई सहायक',
    ai_subtitle: 'वैधानिक सेवाएं एवं भू-कर ज्ञान',
    ai_input_placeholder: 'पट्टा, यूलपिन, ईसी या सेवाओं के बारे में पूछें...',
    ai_listening: 'आवाज सुनी जा रही है... अपना प्रश्न स्पष्ट बोलें',
    ai_disclaimer: 'लैंडस्टैक वैधानिक सेवाओं और भारतीय भू-अभिलेखों में विशेष।',
    status_submitted: 'जमा किया गया',
    status_under_review: 'समीक्षाधीन',
    status_pending_documents: 'दस्तावेज़ लंबित',
    status_field_verification: 'क्षेत्र निरीक्षण',
    status_verified: 'सत्यापित',
    status_supervisor_review: 'अंतिम समीक्षा',
    status_approved: 'स्वीकृत',
    status_completed: 'पूर्ण',
    status_rejected: 'अस्वीकृत',

    // 10 Departments
    dept_1_title: 'राजस्व विभाग',
    dept_1_sub: 'भूमि प्रशासन, पट्टा रजिस्टर और जमाबंदी रिकॉर्ड',
    dept_2_title: 'सर्वेक्षण एवं भू-अभिलेख विभाग',
    dept_2_sub: 'कैडस्ट्रल जीआईएस मानचित्र, एफएमबी स्केच और सीमाएं',
    dept_3_title: 'पंजीकरण विभाग',
    dept_3_sub: 'पंजीकृत लेनदेन, भार प्रमाण पत्र (ईसी) और विलेख',
    dept_4_title: 'स्थानीय निकाय',
    dept_4_sub: 'पंचायत / नगरपालिका संपत्ति कर और मूल्यांकन',
    dept_5_title: 'लोक निर्माण विभाग (पीडब्ल्यूडी)',
    dept_5_sub: 'सड़कें, नहरें, आरओडब्ल्यू संरेखण और बुनियादी ढांचा',
    dept_6_title: 'नगर निगम प्रशासन',
    dept_6_sub: 'शहरी संपत्तियां, भवन निर्माण अनुमति और नागरिक सुविधाएं',
    dept_7_title: 'कृषि एवं वन विभाग',
    dept_7_sub: 'मिट्टी/फसल वर्गीकरण और संरक्षित वन बफर जोन',
    dept_8_title: 'विद्युत विभाग',
    dept_8_sub: 'विद्युत उपयोगिताएं, पोल आईडी और ट्रांसफार्मर',
    dept_9_title: 'पर्यावरण प्राधिकरण',
    dept_9_sub: 'सीआरजेड, आर्द्रभूमि, बाढ़ क्षेत्र और मंजूरी',
    dept_10_title: 'नगर एवं ग्राम नियोजन',
    dept_10_sub: 'मास्टर प्लान ज़ोनिंग, एफएसआई/एफएआर और अनुमतियां'
  },
  te: {
    brand_tagline: 'స్మార్ట్ ల్యాండ్ గవర్నెన్స్ ప్లాట్‌ఫాం',
    active_workspace: 'యాక్టివ్ వర్క్‌స్పేస్',
    citizen_portal: 'పౌరుల పోర్టల్',
    administration: 'పరిపాలన',
    dept_operations: 'విభాగా కార్యకలాపాలు',
    cadastral_inspections: 'భూ సర్వే తనిఖీలు',
    cadastral_tools: 'కాడాస్ట్రల్ ఉపకరణాలు',
    dashboard: 'పౌరుల డాష్‌బోర్డ్',
    my_applications: 'నా దరఖాస్తులు',
    apply_services: 'సేవల కోసం దరఖాస్తు చేయండి',
    cadastral_map: 'కాడాస్ట్రల్ జిఐఎస్ మ్యాప్',
    services: 'ప్రభుత్వ సేవలు',
    profile: 'ప్రొఫైల్ & భద్రత',
    logout: 'లాగ్ అవుట్',
    verified_portal: 'ధృవీకరించబడిన పౌరుల పోర్టల్',
    greeting: 'నమస్కారం',
    welcome_msg: 'సమగ్ర ల్యాండ్‌స్టాక్ వర్క్‌స్పేస్‌కు స్వాగతం. భూ రికార్డులను పరిశీలించండి మరియు దరఖాస్తులను ట్రాక్ చేయండి.',
    apply_for_service: 'సేవకు దరఖాస్తు చేయండి',
    view_records: 'రికార్డులను వీక్షించండి',
    quick_search: 'త్వరిత శోధన:',
    search_cadastre: 'భూ రికార్డులను శోధించండి',
    universal_search_title: 'సమగ్ర భూ పార్సెల్ శోధన — 10 చట్టబద్ధమైన విభాగాలు',
    universal_search_desc: 'అన్ని 10 విభాగాలలో రికార్డులను వీక్షించడానికి ULPIN, సర్వే నంబర్ లేదా ఆధార్ ద్వారా శోధించండి.',
    enter_search_placeholder: 'ULPIN, సర్వే నంబర్ (ఉదా. 124/3B), లేదా ఆధార్ నంబర్ నమోదు చేయండి...',
    all_10_departments: '10 చట్టబద్ధమైన విభాగాలు',
    unified_records_title: '10 విభాగాల సమగ్ర కార్డు రికార్డులు',
    hide_records: 'రికార్డులను దాచండి',
    show_records: 'రికార్డులను చూపించు',
    statutory_records_title: 'చట్టబద్ధమైన విభాగ రికార్డులు',
    statutory_records_desc: 'వివరాలు చూడటానికి క్రింది ఏదైనా విభాగం కార్డును ఎంచుకోండి.',
    view_details: 'వివరాలు చూడండి',
    parameters: 'పారామితులు',
    dept_prefix: 'విభాగం',
    bhu_aadhaar_ulpin: 'భూ-ఆధార్ ULPIN',
    integrated_cadastre_subtitle: '10 చట్టబద్ధమైన విభాగాల సమగ్ర కాడాస్ట్రే',
    ulpin_label: 'ULPIN',
    survey_label: 'సర్వే నం.',
    owner_label: 'యజమాని',
    aadhaar_label: 'ఆధార్',
    owner_name: 'యజమాని పేరు',
    masked_aadhaar: 'ఆధార్ నంబర్',
    survey_subdiv: 'సర్వే / ఉప విభాగం',
    location: 'ప్రాంతం',
    inspect_map: 'మ్యాప్‌లో వీక్షించండి',
    print_records: 'ప్రింట్ రికార్డులు',
    verified_footnote: 'జాతీయ భూ రిపోజిటరీ ద్వారా ధృవీకరించబడింది.',
    press_esc_close: 'మూసివేయడానికి పైన ✕ నొక్కండి',
    my_applications_title: 'నా సేవా దరఖాస్తులు',
    my_applications_desc: 'లైవ్ దరఖాస్తు స్థితి ట్రాకింగ్',
    view_all: 'అన్నీ చూడండి',
    col_app_number: 'దరఖాస్తు సంఖ్య',
    col_service: 'సేవ',
    col_ulpin: 'పార్సెల్ ULPIN',
    col_dept: 'విభాగం',
    col_status: 'స్థితి',
    col_applied_date: 'దరఖాస్తు తేదీ',
    col_action: 'చర్య',
    track_action: 'ట్రాక్ చేయండి',
    ai_assistant: 'ల్యాండ్‌స్టాక్ AI సహాయకుడు',
    ask_ai: 'AI సహాయకుడిని అడగండి',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    syncing: 'సింక్ అవుతోంది',
    select_language: 'భాషను మార్చండి',
    role_citizen: 'పౌరుడు',
    role_supervisor: 'పర్యవేక్షకుడు',
    role_field_officer: 'ఫీల్డ్ ఆఫీసర్',
    role_admin: 'నిర్వాహకుడు',
    notifications: 'నోటిఫికేషన్‌లు',
    mark_all_read: 'అన్నీ చదివినట్లు గుర్తించండి',
    no_notifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    signed_in_as: 'గా సైన్ ఇన్ అయ్యారు',
    agriculture_section: 'వ్యవసాయ విభాగం',
    agriculture_section_sub: 'పంట విధానాలు, నీటిపారుదల వనరులు',
    forest_section: 'అటవీ విభాగం',
    forest_section_sub: 'అటవీ సరిహద్దులు మరియు బఫర్ జోన్లు',
    ai_sahayak: 'AI సహాయకుడు',
    ai_subtitle: 'చట్టబద్ధమైన సేవలు & కాడాస్ట్రల్ సమాచారం',
    ai_input_placeholder: 'పట్టా, ULPIN, EC లేదా సేవల గురించి అడగండి...',
    ai_listening: 'వినబడుతోంది... మీ ప్రశ్నను స్పష్టంగా చెప్పండి',
    ai_disclaimer: 'ల్యాండ్‌స్టాక్ చట్టబద్ధమైన సేవలు మరియు భారతీయ భూ రికార్డులలో ప్రత్యేకమైనది.',
    status_submitted: 'సమర్పించబడింది',
    status_under_review: 'పరిశీలనలో ఉంది',
    status_pending_documents: 'పత్రాలు పెండింగ్‌లో ఉన్నాయి',
    status_field_verification: 'క్షేత్ర తనిఖీ',
    status_verified: 'ధృవీకరించబడింది',
    status_supervisor_review: 'తుది సమీక్ష',
    status_approved: 'ఆమోదించబడింది',
    status_completed: 'పూర్తయింది',
    status_rejected: 'తిరస్కరించబడింది',

    dept_1_title: 'రెవెన్యూ విభాగం',
    dept_1_sub: 'భూ పరిపాలన, పట్టా రికార్డులు',
    dept_2_title: 'సర్వే & భూ రికార్డుల విభాగం',
    dept_2_sub: 'కాడాస్ట్రల్ మ్యాప్, FMB స్కెచ్',
    dept_3_title: 'రిజిస్ట్రేషన్ విభాగం',
    dept_3_sub: 'రిజిస్టర్డ్ లావాదేవీలు, ఎన్‌కంబరెన్స్ (EC)',
    dept_4_title: 'స్థానిక సంస్థలు',
    dept_4_sub: 'పంచాయతీ / మునిసిపాలిటీ పన్ను మరియు అసెస్‌మెంట్',
    dept_5_title: 'పబ్లిక్ వర్క్స్ డిపార్ట్‌మెంట్ (PWD)',
    dept_5_sub: 'రోడ్లు, కాలువలు మరియు మౌలిక సదుపాయాలు',
    dept_6_title: 'మున్సిపల్ అడ్మినిస్ట్రేషన్',
    dept_6_sub: 'పట్టణ ఆస్తులు, భవన అనుమతులు',
    dept_7_title: 'వ్యవసాయం & అటవీ విభాగం',
    dept_7_sub: 'నేల/పంట వర్గీకరణ మరియు అటవీ బఫర్ జోన్లు',
    dept_8_title: 'విద్యుత్ శాఖ',
    dept_8_sub: 'విద్యుత్ యుటిలిటీస్ మరియు ట్రాన్స్‌ఫార్మర్లు',
    dept_9_title: 'పర్యావరణ అధికారులు',
    dept_9_sub: 'CRZ, చిత్తడి నేలలు మరియు అనుమతులు',
    dept_10_title: 'పట్టణ ప్రణాళికా విభాగం',
    dept_10_sub: 'మాస్టర్ ప్లాన్ జోనింగ్, FSI మరియు అనుమతులు'
  },
  kn: {
    brand_tagline: 'ಸ್ಮಾರ್ಟ್ ಭೂ ಆಡಳಿತ ವೇದಿಕೆ',
    active_workspace: 'ಸಕ್ರಿಯ ಕಾರ್ಯಕ್ಷೇತ್ರ',
    citizen_portal: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    administration: 'ಆಡಳಿತ',
    dept_operations: 'ಇಲಾಖಾ ಕಾರ್ಯಾಚರಣೆಗಳು',
    cadastral_inspections: 'ಭೂ ಸಮೀಕ್ಷೆ ಪರಿಶೀಲನೆ',
    cadastral_tools: 'ಕ್ಯಾಡಾಸ್ಟ್ರಲ್ ಪರಿಕರಗಳು',
    dashboard: 'ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    my_applications: 'ನನ್ನ ಅರ್ಜಿಗಳು',
    apply_services: 'ಸೇವೆಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    cadastral_map: 'ಕ್ಯಾಡಾಸ್ಟ್ರಲ್ ಜಿಐಎಸ್ ನಕ್ಷೆ',
    services: 'ಸರ್ಕಾರಿ ಸೇವೆಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಭದ್ರತೆ',
    logout: 'ಲಾಗ್ ಔಟ್',
    verified_portal: 'ಪರಿಶೀಲಿಸಿದ ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    greeting: 'ನಮಸ್ಕಾರ',
    welcome_msg: 'ಸಮಗ್ರ ಲ್ಯಾಂಡ್‌ಸ್ಟಾಕ್ ಕಾರ್ಯಕ್ಷೇತ್ರಕ್ಕೆ ಸುಸ್ವಾಗತ. ಭೂ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    apply_for_service: 'ಸೇವೆಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    view_records: 'ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    quick_search: 'ತ್ವರಿತ ಹುಡುಕಾಟ:',
    search_cadastre: 'ಭೂ ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ',
    universal_search_title: 'ಸಮಗ್ರ ಭೂ ಪಾರ್ಸೆಲ್ ಹುಡುಕಾಟ — 10 ಶಾಸನಬದ್ಧ ಇಲಾಖೆಗಳು',
    universal_search_desc: 'ಎಲ್ಲಾ 10 ಇಲಾಖೆಗಳ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ULPIN, ಸರ್ವೆ ಸಂಖ್ಯೆ ಅಥವಾ ಆಧಾರ್ ಮೂಲಕ ಹುಡುಕಿ.',
    enter_search_placeholder: 'ULPIN, ಸರ್ವೆ ಸಂಖ್ಯೆ (ಉದಾ. 124/3B), ಅಥವಾ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ...',
    all_10_departments: '10 ಶಾಸನಬದ್ಧ ಇಲಾಖೆಗಳು',
    unified_records_title: '10 ಇಲಾಖೆಗಳ ಸಮಗ್ರ ಕಾರ್ಡ್ ದಾಖಲೆಗಳು',
    hide_records: 'ದಾಖಲೆಗಳನ್ನು ಮರೆಮಾಡಿ',
    show_records: 'ದಾಖಲೆಗಳನ್ನು ತೋರಿಸಿ',
    statutory_records_title: 'ಶಾಸನಬದ್ಧ ಇಲಾಖಾ ದಾಖಲೆಗಳು',
    statutory_records_desc: 'ಪರಿಶೀಲಿಸಿದ ನಿಯತಾಂಕಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಕೆಳಗಿನ ಯಾವುದೇ ಕಾರ್ಡ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    view_details: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    parameters: 'ನಿಯತಾಂಕಗಳು',
    dept_prefix: 'ಇಲಾಖೆ',
    bhu_aadhaar_ulpin: 'ಭೂ-ಆಧಾರ್ ULPIN',
    integrated_cadastre_subtitle: '10 ಶಾಸನಬದ್ಧ ಇಲಾಖೆಗಳ ಸಮಗ್ರ ಕ್ಯಾಡಾಸ್ಟ್ರಲ್',
    ulpin_label: 'ULPIN',
    survey_label: 'ಸರ್ವೆ ನಂ.',
    owner_label: 'ಮಾಲೀಕರು',
    aadhaar_label: 'ಆಧಾರ್',
    owner_name: 'ಮಾಲೀಕರ ಹೆಸರು',
    masked_aadhaar: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
    survey_subdiv: 'ಸರ್ವೆ / ಉಪ ವಿಭಾಗ',
    location: 'ಸ್ಥಳ',
    inspect_map: 'ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    print_records: 'ಮುದ್ರಿಸಿ',
    verified_footnote: 'ರಾಷ್ಟ್ರೀಯ ಭೂ ದಾಖಲೆಗಳ ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.',
    press_esc_close: 'ಮುಚ್ಚಲು ಮೇಲೆ ✕ ಒತ್ತಿ',
    my_applications_title: 'ನನ್ನ ಸೇವಾ ಅರ್ಜಿಗಳು',
    my_applications_desc: 'ಲೈವ್ ಅರ್ಜಿ ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕಿಂಗ್',
    view_all: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    col_app_number: 'ಅರ್ಜಿ ಸಂಖ್ಯೆ',
    col_service: 'ಸೇವೆ',
    col_ulpin: 'ಪಾರ್ಸೆಲ್ ULPIN',
    col_dept: 'ಇಲಾಖೆ',
    col_status: 'ಸ್ಥಿತಿ',
    col_applied_date: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ',
    col_action: 'ಕ್ರಮ',
    track_action: 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    ai_assistant: 'ಲ್ಯಾಂಡ್‌ಸ್ಟಾಕ್ AI ಸಹಾಯಕ',
    ask_ai: 'AI ಸಹಾಯಕರನ್ನು ಕೇಳಿ',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    syncing: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ',
    select_language: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    role_citizen: 'ನಾಗರಿಕ',
    role_supervisor: 'ಮೇಲ್ವಿಚಾರಕ',
    role_field_officer: 'ಕ್ಷೇತ್ರ ಅಧಿಕಾರಿ',
    role_admin: 'ನಿರ್ವಾಹಕ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    mark_all_read: 'ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    no_notifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    signed_in_as: 'ಆಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲಾಗಿದೆ',
    agriculture_section: 'ಕೃಷಿ ವಿಭಾಗ',
    agriculture_section_sub: 'ಬೆಳೆ ಮಾದರಿಗಳು ಮತ್ತು ನೀರಾವರಿ ಮೂಲಗಳು',
    forest_section: 'ಅರಣ್ಯ ವಿಭಾಗ',
    forest_section_sub: 'ಅರಣ್ಯ ಗಡಿಗಳು ಮತ್ತು ಬಫರ್ ವಲಯಗಳು',
    ai_sahayak: 'AI ಸಹಾಯಕ',
    ai_subtitle: 'ಶಾಸನಬದ್ಧ ಸೇವೆಗಳು ಮತ್ತು ಭೂ ಮಾಹಿತಿ',
    ai_input_placeholder: 'ಪಟ್ಟಾ, ULPIN, EC ಅಥವಾ ಸೇವೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    ai_listening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ',
    ai_disclaimer: 'ಲ್ಯಾಂಡ್‌ಸ್ಟಾಕ್ ಶಾಸನಬದ್ಧ ಸೇವೆಗಳು ಮತ್ತು ಭೂ ದಾಖಲೆಗಳಲ್ಲಿ ಪರಿಣತಿ.',
    status_submitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    status_under_review: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    status_pending_documents: 'ದಾಖಲೆಗಳು ಬಾಕಿ ಉಳಿದಿವೆ',
    status_field_verification: 'ಕ್ಷೇತ್ರ ಪರಿಶೀಲನೆ',
    status_verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    status_supervisor_review: 'ಅಂತಿಮ ಪರಿಶೀಲನೆ',
    status_approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    status_completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    status_rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',

    dept_1_title: 'ಕಂದಾಯ ಇಲಾಖೆ',
    dept_1_sub: 'ಭೂ ಆಡಳಿತ, ಪಟ್ಟಾ ಮತ್ತು ಜಮಾಬಂದಿ ದಾಖಲೆಗಳು',
    dept_2_title: 'ಸಮೀಕ್ಷೆ ಮತ್ತು ಭೂ ದಾಖಲೆಗಳ ಇಲಾಖೆ',
    dept_2_sub: 'ಕ್ಯಾಡಾಸ್ಟ್ರಲ್ ನಕ್ಷೆ, FMB ಸ್ಕೆಚ್ ಮತ್ತು ಗಡಿಗಳು',
    dept_3_title: 'ನೋಂದಣಿ ಇಲಾಖೆ',
    dept_3_sub: 'ನೋಂದಾಯಿತ ವಹಿವಾಟುಗಳು, ಇಸಿ ಮತ್ತು ಪತ್ರಗಳು',
    dept_4_title: 'ಸ್ಥಳೀಯ ಸಂಸ್ಥೆಗಳು',
    dept_4_sub: 'ಪಂಚಾಯತ್ / ಪುರಸಭೆ ಆಸ್ತಿ ತೆರಿಗೆ ಮತ್ತು ಮೌಲ್ಯಮಾಪನ',
    dept_5_title: 'ಲೋಕೋಪಯೋಗಿ ಇಲಾಖೆ (PWD)',
    dept_5_sub: 'ರಸ್ತೆಗಳು, ಕಾಲುವೆಗಳು ಮತ್ತು ಮೂಲಸೌಕರ್ಯ',
    dept_6_title: 'ಪುರಸಭೆ ಆಡಳಿತ',
    dept_6_sub: 'ನಗರ ಆಸ್ತಿಗಳು, ಕಟ್ಟಡ ಪರವಾನಗಿಗಳು',
    dept_7_title: 'ಕೃಷಿ ಮತ್ತು ಅರಣ್ಯ ಇಲಾಖೆ',
    dept_7_sub: 'ಮಣ್ಣು/ಬೆಳೆ ವರ್ಗೀಕರಣ ಮತ್ತು ಅರಣ್ಯ ಬಫರ್ ವಲಯಗಳು',
    dept_8_title: 'ವಿದ್ಯುತ್ ಇಲಾಖೆ',
    dept_8_sub: 'ವಿದ್ಯುತ್ ಉಪಯುಕ್ತತೆಗಳು ಮತ್ತು ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್‌ಗಳು',
    dept_9_title: 'ಪರಿಸರ ಪ್ರಾಧಿಕಾರಗಳು',
    dept_9_sub: 'ಸಿಆರ್‌ಝೆಡ್, ಜೌಗು ಪ್ರದೇಶಗಳು ಮತ್ತು ಅನುಮತಿಗಳು',
    dept_10_title: 'ನಗರ ಮತ್ತು ಗ್ರಾಮಾಂತರ ಯೋಜನಾ ಇಲಾಖೆ',
    dept_10_sub: 'ಮಾಸ್ಟರ್ ಪ್ಲಾನ್ ವಲಯ, ಎಫ್‌ಎಸ್‌ಐ ಮತ್ತು ಅನುಮತಿಗಳು'
  },
  ml: {
    brand_tagline: 'സ്മാർട്ട് ലാൻഡ് ഗവേണൻസ് പ്ലാറ്റ്ഫോം',
    active_workspace: 'സജീവ വർക്ക്‌സ്‌പെയ്‌സ്',
    citizen_portal: 'പൗര പോർട്ടൽ',
    administration: 'ഭരണകൂടം',
    dept_operations: 'വകുപ്പ് പ്രവർത്തനങ്ങൾ',
    cadastral_inspections: 'ഭൂമി സർവേ പരിശോധനകൾ',
    cadastral_tools: 'സർവേ ഉപകരണങ്ങൾ',
    dashboard: 'പൗര ഡാഷ്‌ബോർഡ്',
    my_applications: 'എന്റെ അപേക്ഷകൾ',
    apply_services: 'സേവനങ്ങൾക്കായി അപേക്ഷിക്കുക',
    cadastral_map: 'കഡാസ്ട്രൽ ജിഐഎസ് മാപ്പ്',
    services: 'സർക്കാർ സേവനങ്ങൾ',
    profile: 'പ്രൊഫൈൽ & സുരക്ഷ',
    logout: 'ലോഗ് ഔട്ട്',
    verified_portal: 'സ്ഥിരീകരിച്ച പൗര പോർട്ടൽ',
    greeting: 'നമസ്കാരം',
    welcome_msg: 'ലാൻഡ്‌സ്റ്റാക്ക് പ്ലാറ്റ്‌ഫോമിലേക്ക് സ്വാഗതം. ഭൂമി രേഖകൾ പരിശോധിക്കുകയും അപേക്ഷകൾ ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക.',
    apply_for_service: 'സേവനത്തിനായി അപേക്ഷിക്കുക',
    view_records: 'രേഖകൾ കാണുക',
    quick_search: 'പെട്ടെന്നുള്ള തിരയൽ:',
    search_cadastre: 'ഭൂമി രേഖകൾ തിരയുക',
    universal_search_title: 'ഭൂമി പാഴ്സൽ തിരയൽ — 10 നിയമാനുസൃത വകുപ്പുകൾ',
    universal_search_desc: '10 വകുപ്പുകളിലെയും രേഖകൾ പരിശോധിക്കാൻ ULPIN, സർവേ നമ്പർ അല്ലെങ്കിൽ ആധാർ നമ്പർ നൽകുക.',
    enter_search_placeholder: 'ULPIN, സർവേ നമ്പർ (ഉദാ. 124/3B), അല്ലെങ്കിൽ ആധാർ നൽകുക...',
    all_10_departments: '10 നിയമാനുസൃത വകുപ്പുകൾ',
    unified_records_title: '10 വകുപ്പുകളുടെ ഏകീകൃത കാർഡ് രേഖകൾ',
    hide_records: 'രേഖകൾ മറയ്ക്കുക',
    show_records: 'രേഖകൾ കാണിക്കുക',
    statutory_records_title: 'നിയമാനുസൃത വകുപ്പ് രേഖകൾ',
    statutory_records_desc: 'വിശദാംശങ്ങൾ കാണാൻ താഴെയുള്ള ഏതെങ്കിലും കാർഡ് തിരഞ്ഞെടുക്കുക.',
    view_details: 'വിശദാംശങ്ങൾ കാണുക',
    parameters: 'അളവുകൾ',
    dept_prefix: 'വകുപ്പ്',
    bhu_aadhaar_ulpin: 'ഭൂ-ആധാർ ULPIN',
    integrated_cadastre_subtitle: '10 നിയമാനുസൃത വകുപ്പുകളുടെ സംയോജിത കാഡസ്ട്രൽ',
    ulpin_label: 'ULPIN',
    survey_label: 'സർവേ നമ്പർ',
    owner_label: 'ഉടമ',
    aadhaar_label: 'ആധാർ',
    owner_name: 'ഉടമയുടെ പേര്',
    masked_aadhaar: 'ആധാർ നമ്പർ',
    survey_subdiv: 'സർവേ / ഉപവിഭാഗം',
    location: 'സ്ഥലം',
    inspect_map: 'മാപ്പിൽ കാണുക',
    print_records: 'പ്രിന്റ് ചെയ്യുക',
    verified_footnote: 'ദേശീയ ഭൂമി രേഖകൾ പ്രകാരം പരിശോധിച്ചു.',
    press_esc_close: 'അടയ്ക്കാൻ മുകളിൽ ✕ അമർത്തുക',
    my_applications_title: 'എന്റെ സേവന അപേക്ഷകൾ',
    my_applications_desc: 'തത്സമയ അപേക്ഷാ ട്രാക്കിംഗ്',
    view_all: 'എല്ലാം കാണുക',
    col_app_number: 'അപേക്ഷാ നമ്പർ',
    col_service: 'സേവനം',
    col_ulpin: 'പാഴ്സൽ ULPIN',
    col_dept: 'വകുപ്പ്',
    col_status: 'നില',
    col_applied_date: 'അപേക്ഷിച്ച തീയതി',
    col_action: 'നടപടി',
    track_action: 'ട്രാക്ക് ചെയ്യുക',
    ai_assistant: 'ലാൻഡ്‌സ്റ്റാക്ക് AI അസിസ്റ്റന്റ്',
    ask_ai: 'AI അസിസ്റ്റന്റിനോട് ചോദിക്കുക',
    online: 'ഓൺലൈൻ',
    offline: 'ഓഫ്‌ലൈൻ',
    syncing: 'സിങ്ക് ചെയ്യുന്നു',
    select_language: 'ഭാഷ മാറ്റുക',
    role_citizen: 'പൗരൻ',
    role_supervisor: 'സൂപ്പർവൈസർ',
    role_field_officer: 'ഫീൽഡ് ഓഫീസർ',
    role_admin: 'അഡ്മിൻ',
    notifications: 'അറിയിപ്പുകൾ',
    mark_all_read: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    no_notifications: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല',
    signed_in_as: 'ആയി സൈൻ ഇൻ ചെയ്തു',
    agriculture_section: 'കൃഷി വിഭാഗം',
    agriculture_section_sub: 'വിള രീതികളും ജലസേചന സ്രോതസ്സുകളും',
    forest_section: 'വനം വിഭാഗം',
    forest_section_sub: 'വന അതിർത്തികളും ബഫർ സോണുകളും',
    ai_sahayak: 'AI അസിസ്റ്റന്റ്',
    ai_subtitle: 'നിയമാനുസൃത സേവനങ്ങളും വിവരങ്ങളും',
    ai_input_placeholder: 'പട്ടയം, ULPIN, EC അല്ലെങ്കിൽ സേവനങ്ങളെക്കുറിച്ച് ചോദിക്കുക...',
    ai_listening: 'ശ്രദ്ധിക്കുന്നു... ചോദ്യം വ്യക്തമായി പറയുക',
    ai_disclaimer: 'ലാൻഡ്‌സ്റ്റാക്ക് സേവനങ്ങളിലും രേഖകളിലും പ്രത്യേകമായത്.',
    status_submitted: 'സമർപ്പിച്ചു',
    status_under_review: 'പരിശോധനയിൽ',
    status_pending_documents: 'രേഖകൾ ബാക്കിയുണ്ട്',
    status_field_verification: 'ഫീൽഡ് പരിശോധന',
    status_verified: 'സ്ഥിരീകരിച്ചു',
    status_supervisor_review: 'അന്തിമ അവലോകനം',
    status_approved: 'അംഗീകരിച്ചു',
    status_completed: 'പൂർത്തിയായി',
    status_rejected: 'നിരസിച്ചു',

    dept_1_title: 'റവന്യൂ വകുപ്പ്',
    dept_1_sub: 'ഭൂമി ഭരണം, പട്ടയം രേഖകൾ',
    dept_2_title: 'സർവേയും ഭൂമി രേഖകളും വകുപ്പ്',
    dept_2_sub: 'കഡാസ്ട്രൽ മാപ്പ്, അതിരുകൾ',
    dept_3_title: 'രജിസ്ട്രേഷൻ വകുപ്പ്',
    dept_3_sub: 'രജിസ്റ്റർ ചെയ്ത ഇടപാടുകൾ, ബാധ്യത സർട്ടിഫിക്കറ്റ് (EC)',
    dept_4_title: 'തദ്ദേശ സ്വയംഭരണ സ്ഥാപനങ്ങൾ',
    dept_4_sub: 'പഞ്ചായത്ത് / മുനിസിപ്പാലിറ്റി വസ്തു നികുതി',
    dept_5_title: 'പൊതുമരാമത്ത് വകുപ്പ് (PWD)',
    dept_5_sub: 'റോഡുകൾ, കനാലുകൾ, വികസനം',
    dept_6_title: 'മുനിസിപ്പൽ അഡ്മിനിസ്ട്രേഷൻ',
    dept_6_sub: 'നഗര സ്വത്തുക്കൾ, കെട്ടിട അനുമതികൾ',
    dept_7_title: 'കൃഷി, വനം വകുപ്പ്',
    dept_7_sub: 'മണ്ണ്/വിള വർഗ്ഗീകരണം, സംരക്ഷിത വനങ്ങൾ',
    dept_8_title: 'വൈദ്യുതി വകുപ്പ്',
    dept_8_sub: 'വൈദ്യുതി യൂട്ടിലിറ്റികൾ, ട്രാൻസ്ഫോർമറുകൾ',
    dept_9_title: 'പരിസ്ഥിതി അധികാരികൾ',
    dept_9_sub: 'സിആർസെഡ്, തണ്ണീർത്തടങ്ങൾ, ക്ലിയറൻസ്',
    dept_10_title: 'നഗര-ഗ്രാമാസൂത്രണ വകുപ്പ്',
    dept_10_sub: 'മാസ്റ്റർ പ്ലാൻ സോണിംഗ്, എഫ്എസ്ഐ'
  },
  bn: {
    brand_tagline: 'স্মার্ট ভূমি শাসন প্ল্যাটফর্ম',
    active_workspace: 'সক্রিয় কর্মক্ষেত্র',
    citizen_portal: 'নাগরিক পোর্টাল',
    administration: 'প্রশাসন',
    dept_operations: 'বিভাগীয় পরিচালনা',
    cadastral_inspections: 'ভূমি জরিপ পরিদর্শন',
    cadastral_tools: 'ক্যাডাস্ট্রাল সরঞ্জাম',
    dashboard: 'নাগরিক ড্যাশবোর্ড',
    my_applications: 'আমার আবেদনসমূহ',
    apply_services: 'পরিষেবার জন্য আবেদন করুন',
    cadastral_map: 'ক্যাডাস্ট্রাল জিআইএস মানচিত্র',
    services: 'সরকারি পরিষেবা',
    profile: 'প্রোফাইল ও নিরাপত্তা',
    logout: 'লগ আউট',
    verified_portal: 'যাচাইকৃত নাগরিক পোর্টাল',
    greeting: 'নমস্কার',
    welcome_msg: 'সমন্বিত ল্যান্ডস্ট্যাক প্ল্যাটফর্মে স্বাগতম। জমির রেকর্ড পরীক্ষা করুন এবং রিয়েল-টাইমে আবেদন ট্র্যাক করুন।',
    apply_for_service: 'আবেদন করুন',
    view_records: 'নথিপত্র দেখুন',
    quick_search: 'দ্রুত অনুসন্ধান:',
    search_cadastre: 'ভূমি রেকর্ড অনুসন্ধান',
    universal_search_title: 'সার্বজনীন ভূমি পার্সেল অনুসন্ধান — ১০টি সংবিধিবদ্ধ বিভাগ',
    universal_search_desc: 'সকল ১০টি সংবিধিবদ্ধ বিভাগের রেকর্ড দেখতে ULPIN, দাগ/সার্ভে নম্বর বা আধার দিয়ে খুঁজুন।',
    enter_search_placeholder: 'ULPIN, সার্ভে নম্বর (যেমন 124/3B), অথবা আধার নম্বর লিখুন...',
    all_10_departments: '১০টি সংবিধিবদ্ধ বিভাগ',
    unified_records_title: '১০টি বিভাগের সমন্বিত কার্ড রেকর্ড',
    hide_records: 'লুকান',
    show_records: 'রেকর্ড দেখুন',
    statutory_records_title: 'সংবিধিবদ্ধ বিভাগের রেকর্ড',
    statutory_records_desc: 'বিস্তারিত যাচাইকৃত পরামিতি দেখতে নিচের যেকোনো কার্ডে ক্লিক করুন।',
    view_details: 'বিস্তারিত দেখুন',
    parameters: 'পরামিতি',
    dept_prefix: 'বিভাগ',
    bhu_aadhaar_ulpin: 'ভূ-আধার ULPIN',
    integrated_cadastre_subtitle: '১০টি সংবিধিবদ্ধ বিভাগের সমন্বিত ক্যাডাস্ট্রাল',
    ulpin_label: 'ULPIN',
    survey_label: 'সার্ভে নং',
    owner_label: 'মালিক',
    aadhaar_label: 'আধার',
    owner_name: 'মালিকের নাম',
    masked_aadhaar: 'আধার নম্বর',
    survey_subdiv: 'সার্ভে / উপ-বিভাগ',
    location: 'অবস্থান',
    inspect_map: 'মানচিত্রে দেখুন',
    print_records: 'প্রিন্ট করুন',
    verified_footnote: 'জাতীয় ক্যাডাস্ট্রাল রিপোজিটরি দ্বারা যাচাইকৃত।',
    press_esc_close: 'বন্ধ করতে উপরে ✕ চাপুন',
    my_applications_title: 'আমার সেবা আবেদনসমূহ',
    my_applications_desc: 'লাইভ সংবিধিবদ্ধ আবেদন ট্র্যাকিং',
    view_all: 'সব দেখুন',
    col_app_number: 'আবেদন নম্বর',
    col_service: 'সেবা',
    col_ulpin: 'পার্সেল ULPIN',
    col_dept: 'বিভাগ',
    col_status: 'স্থিতি',
    col_applied_date: 'আবেদনের তারিখ',
    col_action: 'পদক্ষেপ',
    track_action: 'ট্র্যাক করুন',
    ai_assistant: 'ল্যান্ডস্ট্যাক এআই সহকারী',
    ask_ai: 'এআই সহকারীকে জিজ্ঞাসা করুন',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    syncing: 'সিঙ্ক হচ্ছে',
    select_language: 'ভাষা পরিবর্তন',
    role_citizen: 'নাগরিক',
    role_supervisor: 'তত্ত্বাবধায়ক',
    role_field_officer: 'ফিল্ড অফিসার',
    role_admin: 'প্রশাসক',
    notifications: 'বিজ্ঞপ্তি',
    mark_all_read: 'সব পঠিত চিহ্নিত করুন',
    no_notifications: 'কোন নতুন বিজ্ঞপ্তি নেই',
    signed_in_as: 'হিসাবে সাইন ইন করেছেন',
    agriculture_section: 'কৃষি বিভাগ',
    agriculture_section_sub: 'ফসলের ধরন ও সেচ উৎস',
    forest_section: 'বন বিভাগ',
    forest_section_sub: 'বনের সীমানা ও বাফার জোন',
    ai_sahayak: 'এআই সহায়ক',
    ai_subtitle: 'সংবিধিবদ্ধ পরিষেবা ও তথ্য',
    ai_input_placeholder: 'পাট্টা, ULPIN, EC বা সেবা সম্পর্কে জিজ্ঞাসা করুন...',
    ai_listening: 'শুনছি... আপনার প্রশ্ন স্পষ্ট করে বলুন',
    ai_disclaimer: 'ল্যান্ডস্ট্যাক সংবিধিবদ্ধ সেবা ও ভারতীয় ভূমি রেকর্ডে বিশেষজ্ঞ।',
    status_submitted: 'জমা দেওয়া হয়েছে',
    status_under_review: 'পর্যালোচনাধীন',
    status_pending_documents: 'নথিপত্র মুলতুবি',
    status_field_verification: 'মাঠ পরিদর্শন',
    status_verified: 'যাচাইকৃত',
    status_supervisor_review: 'চূড়ান্ত পর্যালোচনা',
    status_approved: 'অনুমোদিত',
    status_completed: 'সম্পন্ন',
    status_rejected: 'প্রত্যাখ্যাত',

    dept_1_title: 'রাজস্ব বিভাগ',
    dept_1_sub: 'ভূমি প্রশাসন, পাট্টা রেজিস্টার ও রেকর্ড',
    dept_2_title: 'জরিপ ও ভূমি রেকর্ড বিভাগ',
    dept_2_sub: 'ক্যাডাস্ট্রাল ম্যাপ, এফএমবি স্কেচ ও সীমানা',
    dept_3_title: 'নিবন্ধন বিভাগ',
    dept_3_sub: 'নিবন্ধিত লেনদেন, দায়বদ্ধতা সার্টিফিকেট (EC)',
    dept_4_title: 'স্থানীয় সংস্থা',
    dept_4_sub: 'পঞ্চায়েত / পৌরসভা সম্পত্তি কর ও মূল্যায়ন',
    dept_5_title: 'গণপূর্ত বিভাগ (PWD)',
    dept_5_sub: 'রাস্তাঘাট, খাল ও অবকাঠামো সম্প্রসারণ',
    dept_6_title: 'পৌর প্রশাসন',
    dept_6_sub: 'শহুরে সম্পত্তি, ভবন নির্মাণ অনুমতি',
    dept_7_title: 'কৃষি ও বন বিভাগ',
    dept_7_sub: 'মাটি/ফসল শ্রেণিবিভাগ ও সংরক্ষিত বন বাফার জোন',
    dept_8_title: 'বিদ্যুৎ বিভাগ',
    dept_8_sub: 'বিদ্যুৎ সংযোগ ও ট্রান্সফরমার',
    dept_9_title: 'পরিবেশ কর্তৃপক্ষ',
    dept_9_sub: 'সিআরজেড, জলাভূমি এবং ছাড়পত্র',
    dept_10_title: 'নগর ও গ্রাম পরিকল্পনা বিভাগ',
    dept_10_sub: 'মাস্টার প্ল্যান জোনিং, এফএসআই ও অনুমতি'
  },
  mr: {
    brand_tagline: 'स्मार्ट भू-प्रशासन व्यासपीठ',
    active_workspace: 'सक्रिय कार्यक्षेत्र',
    citizen_portal: 'नागरिक पोर्टल',
    administration: 'प्रशासन',
    dept_operations: 'विभागीय कामकाज',
    cadastral_inspections: 'जमीन सर्वेक्षण तपासणी',
    cadastral_tools: 'कॅडस्ट्रल साधने',
    dashboard: 'नागरिक डॅशबोर्ड',
    my_applications: 'माझे अर्ज',
    apply_services: 'सेवा मिळवण्यासाठी अर्ज करा',
    cadastral_map: 'कॅडस्ट्रल जीआयएस नकाशा',
    services: 'शासकीय सेवा',
    profile: 'प्रोफाइल आणि सुरक्षा',
    logout: 'लॉग आउट',
    verified_portal: 'प्रमाणित नागरिक पोर्टल',
    greeting: 'नमस्कार',
    welcome_msg: 'लँडस्टॅक प्लॅटफॉर्मवर आपले स्वागत आहे. जमीन नोंदी तपासा आणि अर्जांची सद्यस्थिती पहा.',
    apply_for_service: 'सेवेसाठी अर्ज करा',
    view_records: 'नोंदी पहा',
    quick_search: 'जलद शोध:',
    search_cadastre: 'जमीन नोंदी शोधा',
    universal_search_title: 'सार्वत्रिक जमीन पार्सल शोध — १० वैधानिक विभाग',
    universal_search_desc: '१० वैधानिक विभागांमधील नोंदी पाहण्यासाठी ULPIN, सर्व्हे क्रमांक किंवा आधार क्रमांकाने शोधा.',
    enter_search_placeholder: 'ULPIN, सर्व्हे क्रमांक (उदा. 124/3B), किंवा आधार क्रमांक टाका...',
    all_10_departments: '१० वैधानिक विभाग',
    unified_records_title: '१० विभागांच्या एकत्रित कार्ड नोंदी',
    hide_records: 'नोंदी लपवा',
    show_records: 'नोंदी दाखवा',
    statutory_records_title: 'वैधानिक विभाग नोंदी',
    statutory_records_desc: 'तपशीलवार तपासलेले घटक पाहण्यासाठी खालील कोणत्याही कार्डवर क्लिक करा.',
    view_details: 'तपशील पहा',
    parameters: 'घटक',
    dept_prefix: 'विभाग',
    bhu_aadhaar_ulpin: 'भू-आधार ULPIN',
    integrated_cadastre_subtitle: '१० वैधानिक विभागांचा एकात्मिक कॅडस्ट्रल',
    ulpin_label: 'ULPIN',
    survey_label: 'सर्व्हे क्र.',
    owner_label: 'मालक',
    aadhaar_label: 'आधार',
    owner_name: 'मालकाचे नाव',
    masked_aadhaar: 'आधार क्रमांक',
    survey_subdiv: 'सर्व्हे / उप-विभाग',
    location: 'ठिकाण',
    inspect_map: 'नकाशावर पहा',
    print_records: 'प्रिंट करा',
    verified_footnote: 'राष्ट्रीय भू-कर भांडाराद्वारे सत्यापित.',
    press_esc_close: 'बंद करण्यासाठी वर ✕ दाबा',
    my_applications_title: 'माझे सेवा अर्ज',
    my_applications_desc: 'थेट वैधानिक अर्ज ट्रॅकिंग',
    view_all: 'सर्व पहा',
    col_app_number: 'अर्ज क्रमांक',
    col_service: 'सेवा',
    col_ulpin: 'पार्सल ULPIN',
    col_dept: 'विभाग',
    col_status: 'स्थिती',
    col_applied_date: 'अर्ज तारीख',
    col_action: 'कृती',
    track_action: 'ट्रॅक करा',
    ai_assistant: 'लँडस्टॅक एआय सहाय्यक',
    ask_ai: 'एआय सहाय्यकाला विचारा',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    syncing: 'सिंक होत आहे',
    select_language: 'भाषा बदला',
    role_citizen: 'नागरिक',
    role_supervisor: 'पर्यवेक्षक',
    role_field_officer: 'क्षेत्र अधिकारी',
    role_admin: 'प्रशासक',
    notifications: 'सूचना',
    mark_all_read: 'सर्व वाचलेले चिन्हांकित करा',
    no_notifications: 'नवीन सूचना नाहीत',
    signed_in_as: 'म्हणून साइन इन केले',
    agriculture_section: 'कृषी विभाग',
    agriculture_section_sub: 'पीक पद्धती आणि सिंचन स्रोत',
    forest_section: 'वन विभाग',
    forest_section_sub: 'वन सीमा आणि बफर झोन',
    ai_sahayak: 'एआय सहाय्यक',
    ai_subtitle: 'वैधानिक सेवा आणि माहिती',
    ai_input_placeholder: 'पट्टा, ULPIN, EC किंवा सेवांबद्दल विचारा...',
    ai_listening: 'ऐकत आहे... तुमचा प्रश्न स्पष्टपणे बोला',
    ai_disclaimer: 'लँडस्टॅक वैधानिक सेवा आणि जमीन नोंदींमध्ये विशेषीकृत.',
    status_submitted: 'सादर केले',
    status_under_review: 'पुनरावलोकनाधीन',
    status_pending_documents: 'कागदपत्रे प्रलंबित',
    status_field_verification: 'क्षेत्र तपासणी',
    status_verified: 'सत्यापित',
    status_supervisor_review: 'अंतिम आढावा',
    status_approved: 'मंजूर',
    status_completed: 'पूर्ण झाले',
    status_rejected: 'नाकारले',

    dept_1_title: 'महसूल विभाग',
    dept_1_sub: 'जमीन प्रशासन, पट्टा नोंदवही व जमाबंदी',
    dept_2_title: 'भूमापन व भूमी अभिलेख विभाग',
    dept_2_sub: 'कॅडस्ट्रल नकाशा, एफएमबी स्केच आणि सीमा',
    dept_3_title: 'नोंदणी विभाग',
    dept_3_sub: 'नोंदणीकृत व्यवहार, बोजा प्रमाणपत्र (EC)',
    dept_4_title: 'स्थानिक स्वराज्य संस्था',
    dept_4_sub: 'ग्रामपंचायत / नगरपालिका मालमत्ता कर',
    dept_5_title: 'सार्वजनिक बांधकाम विभाग (PWD)',
    dept_5_sub: 'रस्ते, कालवे आणि पायाभूत सुविधा',
    dept_6_title: 'महानगरपालिका प्रशासन',
    dept_6_sub: 'शहरी मालमत्ता, बांधकाम परवानग्या',
    dept_7_title: 'कृषी व वन विभाग',
    dept_7_sub: 'माती/पीक वर्गीकरण आणि संरक्षित वन क्षेत्र',
    dept_8_title: 'विद्युत विभाग',
    dept_8_sub: 'वीज जोडणी आणि ट्रान्सफॉर्मर',
    dept_9_title: 'पर्यावरण प्राधिकरण',
    dept_9_sub: 'सीआरझेड, पाणथळ जागा आणि मंजुरी',
    dept_10_title: 'नगर रचना व नियोजन विभाग',
    dept_10_sub: 'मास्टर प्लॅन झोनिंग, एफएसआय आणि परवानग्या'
  },
  gu: {
    brand_tagline: 'સ્માર્ટ જમીન શાસન પ્લેટફોર્મ',
    active_workspace: 'સક્રિય કાર્યક્ષેત્ર',
    citizen_portal: 'નાગરિક પોર્ટલ',
    administration: 'વહીવટ',
    dept_operations: 'વિભાગીય કામગીરી',
    cadastral_inspections: 'જમીન સર્વેક્ષણ તપાસ',
    cadastral_tools: 'કેડસ્ટ્રલ સાધનો',
    dashboard: 'નાગરિક ડેશબોર્ડ',
    my_applications: 'મારી અરજીઓ',
    apply_services: 'સેવાઓ માટે અરજી કરો',
    cadastral_map: 'કેડસ્ટ્રલ જીઆઈએસ નકશો',
    services: 'સરકારી સેવાઓ',
    profile: 'પ્રોફાઇલ અને સુરક્ષા',
    logout: 'લૉગ આઉટ',
    verified_portal: 'ચકાસાયેલ નાગરિક પોર્ટલ',
    greeting: 'નમસ્તે',
    welcome_msg: 'સંકલિત લેન્ડસ્ટેક કાર્યક્ષેત્રમાં આપનું સ્વાગત છે. જમીન રેકોર્ડની તપાસ કરો અને અરજીઓ ટ્રેક કરો.',
    apply_for_service: 'સેવા માટે અરજી કરો',
    view_records: 'રેકોર્ડ્સ જુઓ',
    quick_search: 'ઝડપી શોધ:',
    search_cadastre: 'જમીન રેકોર્ડ શોધો',
    universal_search_title: 'સાર્વત્રિક જમીન પાર્સલ શોધ — ૧૦ વૈધાનિક વિભાગો',
    universal_search_desc: 'બધા ૧૦ વૈધાનિક વિભાગોના રેકોર્ડ જોવા માટે ULPIN, સર્વે નંબર અથવા આધાર દ્વારા શોધો.',
    enter_search_placeholder: 'ULPIN, સર્વે નંબર (દા.ત. 124/3B), અથવા આધાર નંબર દાખલ કરો...',
    all_10_departments: '૧૦ વૈધાનિક વિભાગો',
    unified_records_title: '૧૦ વિભાગોના સંકલિત કાર્ડ રેકોર્ડ્સ',
    hide_records: 'રેકોર્ડ્સ છુપાવો',
    show_records: 'રેકોર્ડ્સ બતાવો',
    statutory_records_title: 'વૈધાનિક વિભાગ રેકોર્ડ્સ',
    statutory_records_desc: 'ચકાસાયેલ પરિમાણો જોવા માટે નીચેના કોઈપણ કાર્ડ પર ક્લિક કરો.',
    view_details: 'વિગતો જુઓ',
    parameters: 'પરિમાણો',
    dept_prefix: 'વિભાગ',
    bhu_aadhaar_ulpin: 'ભૂ-આધાર ULPIN',
    integrated_cadastre_subtitle: '૧૦ વૈધાનિક વિભાગોનું સંકલિત કેડસ્ટ્રલ',
    ulpin_label: 'ULPIN',
    survey_label: 'સર્વે નં.',
    owner_label: 'માલિક',
    aadhaar_label: 'આધાર',
    owner_name: 'માલિકનું નામ',
    masked_aadhaar: 'આધાર નંબર',
    survey_subdiv: 'સર્વે / પેટા વિભાગ',
    location: 'સ્થળ',
    inspect_map: 'નકશા પર જુઓ',
    print_records: 'પ્રિન્ટ કરો',
    verified_footnote: 'રાષ્ટ્રીય કેડસ્ટ્રલ રિપોઝીટરી દ્વારા ચકાસાયેલ.',
    press_esc_close: 'બંધ કરવા માટે ઉપર ✕ દબાવો',
    my_applications_title: 'મારી સેવા અરજીઓ',
    my_applications_desc: 'લાઈવ અરજી સ્થિતિ ટ્રેકિંગ',
    view_all: 'બધું જુઓ',
    col_app_number: 'અરજી નંબર',
    col_service: 'સેવા',
    col_ulpin: 'પાર્સલ ULPIN',
    col_dept: 'વિભાગ',
    col_status: 'સ્થિતિ',
    col_applied_date: 'અરજી તારીખ',
    col_action: 'પગલાં',
    track_action: 'ટ્રેક કરો',
    ai_assistant: 'લેન્ડસ્ટેક AI સહાયક',
    ask_ai: 'AI સહાયકને પૂછો',
    online: 'ઓનલાઇન',
    offline: 'ઓફલાઇન',
    syncing: 'સિંક થઈ રહ્યું છે',
    select_language: 'ભાષા બદલો',
    role_citizen: 'નાગરિક',
    role_supervisor: 'સુપરવાઇઝર',
    role_field_officer: 'ફિલ્ડ ઓફિસર',
    role_admin: 'એડમિન',
    notifications: 'સૂચનાઓ',
    mark_all_read: 'બધા વાંચેલા તરીકે ચિહ્નિત કરો',
    no_notifications: 'કોઈ નવી સૂચનાઓ નથી',
    signed_in_as: 'તરીકે સાઇન ઇન કર્યું',
    agriculture_section: 'કૃષિ વિભાગ',
    agriculture_section_sub: 'પાકની પદ્ધતિઓ અને સિંચાઈ સ્ત્રોતો',
    forest_section: 'વન વિભાગ',
    forest_section_sub: 'વન સીમાઓ અને બફર ઝોન',
    ai_sahayak: 'AI સહાયક',
    ai_subtitle: 'વૈધાનિક સેવાઓ અને માહિતી',
    ai_input_placeholder: 'પટ્ટા, ULPIN, EC અથવા સેવાઓ વિશે પૂછો...',
    ai_listening: 'સાંભળી રહ્યા છીએ... તમારો પ્રશ્ન સ્પષ્ટ રીતે બોલો',
    ai_disclaimer: 'લેન્ડસ્ટેક વૈધાનિક સેવાઓ અને જમીન રેકોર્ડમાં વિશેષજ્ઞ.',
    status_submitted: 'સબમિટ કર્યું',
    status_under_review: 'સમીક્ષા હેઠળ',
    status_pending_documents: 'દસ્તાવેજો બાકી છે',
    status_field_verification: 'ક્ષેત્ર નિરીક્ષણ',
    status_verified: 'ચકાસાયેલ',
    status_supervisor_review: 'અંતિમ સમીક્ષા',
    status_approved: 'મંજૂર',
    status_completed: 'પૂર્ણ થયું',
    status_rejected: 'નામંજૂર',

    dept_1_title: 'મહેસૂલ વિભાગ',
    dept_1_sub: 'જમીન વહીવટ, પટ્ટા રજિસ્ટર અને જમાબંધી',
    dept_2_title: 'સર્વે અને જમીન દફતર વિભાગ',
    dept_2_sub: 'કેડસ્ટ્રલ નકશો, FMB સ્કેચ અને સીમાઓ',
    dept_3_title: 'નોંધણી વિભાગ',
    dept_3_sub: 'નોંધાયેલ વ્યવહારો, બોજા પ્રમાણપત્ર (EC)',
    dept_4_title: 'સ્થાનિક સંસ્થાઓ',
    dept_4_sub: 'પંચાયત / નગરપાલિકા મિલકત વેરો',
    dept_5_title: 'માર્ગ અને મકાન વિભાગ (PWD)',
    dept_5_sub: 'રસ્તાઓ, નહેરો અને માળખાગત સુવિધાઓ',
    dept_6_title: 'મ્યુનિસિપલ વહીવટ',
    dept_6_sub: 'શહેરી મિલકતો, બાંધકામ મંજૂરીઓ',
    dept_7_title: 'કૃષિ અને વન વિભાગ',
    dept_7_sub: 'જમીન/પાક વર્ગીકરણ અને સંરક્ષિત વન ઝોન',
    dept_8_title: 'વીજળી વિભાગ',
    dept_8_sub: 'વીજળી જોડાણ અને ટ્રાન્સફોર્મર',
    dept_9_title: 'પર્યાવરણ સત્તામંડળ',
    dept_9_sub: 'સીઆરઝેડ, જળપ્લાવિત વિસ્તારો અને મંજૂરીઓ',
    dept_10_title: 'નગર આયોજન વિભાગ',
    dept_10_sub: 'માસ્ટર પ્લાન ઝોનિંગ, એફએસઆઈ અને પરવાનગીઓ'
  }
};

// Parameter and Status Label Translations for the 10 Department Cards & Modal
const PARAM_TRANSLATIONS = {
  ta: {
    'Parcel ID': 'பார்சல் எண்',
    'ULPIN': 'பூ-ஆதார் ULPIN',
    'Patta Number': 'பட்டா எண்',
    'Survey Number': 'சர்வே எண்',
    'Sub-Division Number': 'உட்பிரிவு எண்',
    'Sub-Division': 'உட்பிரிவு',
    'Owner Name': 'உரிமையாளர் பெயர்',
    'Ownership Type': 'உரிமை வகை',
    'Land Area': 'நிலப் பரப்பளவு',
    'Parcel Area': 'பார்சல் பரப்பளவு',
    'Land Classification': 'நில வகைப்பாடு',
    'Land Type': 'நில வகை',
    'Patta Status': 'பட்டா நிலை',
    'Mutation Status': 'பட்டா மாறுதல் நிலை',
    'District': 'மாவட்டம்',
    'Taluk': 'வட்டம் (தாலுகா)',
    'Village': 'கிராமம்',
    'Parcel Boundary': 'பார்சல் எல்லை',
    'Boundary Status': 'எல்லை நிலை',
    'Survey Status': 'அளவை நிலை',
    'Cadastral Map': 'நில அளவை வரைபடம்',
    'FMB Sketch': 'FMB வரைபடம்',
    'Latitude': 'அட்சரேகை',
    'Longitude': 'தீர்க்கரேகை',
    'Adjacent Parcels': 'அருகிலுள்ள பார்சல்கள்',
    'Boundary Coordinates': 'எல்லை ஆயத்தொலைவுகள்',
    'Document Number': 'ஆவண எண்',
    'Document Type': 'ஆவண வகை',
    'Registration Date': 'பதிவு தேதி',
    'Registration Office': 'சார்பதிவாளர் அலுவலகம்',
    'Transaction Type': 'பரிவர்த்தனை வகை',
    'Transferor': 'விற்பனையாளர்',
    'Transferee': 'வாங்குபவர்',
    'Transaction Value': 'பரிவர்த்தனை மதிப்பு',
    'Encumbrance Status': 'வில்லங்க நிலை',
    'Mortgage Status': 'அடமான நிலை',
    'EC Status': 'வில்லங்கச் சான்றிதழ் நிலை',
    'Document Status': 'ஆவண நிலை',
    'Property ID': 'சொத்து எண்',
    'Assessment Number': 'மதிப்பீட்டு எண்',
    'Ward Number': 'வார்டு எண்',
    'Local Body': 'உள்ளாட்சி அமைப்பு',
    'Property Type': 'சொத்து வகை',
    'Property Usage': 'சொத்து பயன்பாடு',
    'Building Status': 'கட்டிட நிலை',
    'Property Tax Status': 'சொத்து வரி நிலை',
    'Tax Amount': 'வரித் தொகை',
    'Tax Arrears': 'வரி நிலுவை',
    'Assessment Status': 'மதிப்பீட்டு நிலை',
    'Infrastructure ID': 'உள்கட்டமைப்பு எண்',
    'Infrastructure Type': 'உள்கட்டமைப்பு வகை',
    'Road/Canal Name': 'சாலை / கால்வாய் பெயர்',
    'Road Width': 'சாலை அகலம்',
    'Right of Way': 'வழி உரிமை (ROW)',
    'Distance from Parcel': 'பார்சலில் இருந்து தூரம்',
    'Affected Area': 'பாதிக்கப்பட்ட பகுதி',
    'Proposed Project': 'திட்ட முன்மொழிவு',
    'Acquisition Status': 'கையகப்படுத்தல் நிலை',
    'Development Restriction': 'வளர்ச்சி கட்டுப்பாடு',
    'Infrastructure Status': 'உள்கட்டமைப்பு நிலை',
    'Municipality/Corporation': 'நகராட்சி / மாநகராட்சி',
    'Zone': 'மண்டலம்',
    'Ward': 'வார்டு',
    'Building Usage': 'கட்டிட பயன்பாடு',
    'Building Permission': 'கட்டிட அனுமதி',
    'Property Tax': 'சொத்து வரி',
    'Water Connection': 'குடிநீர் இணைப்பு',
    'Sewerage Connection': 'பாதாள சாக்கடை இணைப்பு',
    'Solid Waste Service': 'திடக்கழிவு சேவை',
    'Municipal Restriction': 'நகராட்சி கட்டுப்பாடு',
    'Agricultural Land Status': 'விவசாய நில நிலை',
    'Crop Type': 'பயிர் வகை',
    'Soil Type': 'மண் வகை',
    'Irrigation Type': 'பாசன வகை',
    'Irrigated Status': 'பாசன நிலை',
    'Cultivation Status': 'பயிரிடல் நிலை',
    'Agricultural Classification': 'விவசாய வகைப்பாடு',
    'Water Source': 'நீர் ஆதாரம்',
    'Forest Zone ID': 'வன மண்டல எண்',
    'Forest Type': 'வன வகை',
    'Forest Boundary': 'வன எல்லை',
    'Protected Status': 'பாதுகாக்கப்பட்ட நிலை',
    'Distance from Forest': 'வனத்தில் இருந்து தூரம்',
    'Buffer Zone': 'இடையக மண்டலம்',
    'Eco-Sensitive Zone': 'சூழல் உணர்திறன் மண்டலம்',
    'Clearance Required': 'அனுமதி தேவையா',
    'Clearance Status': 'அனுமதி நிலை',
    'Connection ID': 'இணைப்பு எண்',
    'Consumer ID': 'நுகர்வோர் எண்',
    'Connection Status': 'இணைப்பு நிலை',
    'Connection Type': 'இணைப்பு வகை',
    'Transformer ID': 'மின்மாற்றி எண்',
    'Pole ID': 'மின்கம்ப எண்',
    'Power Line': 'மின்பாதை',
    'Voltage Level': 'மின்னழுத்த அளவு',
    'Distance from Transformer': 'மின்மாற்றி தூரம்',
    'Utility Corridor': 'பயன்பாட்டு பாதை',
    'Environmental Zone': 'சுற்றுச்சூழல் மண்டலம்',
    'CRZ Status': 'CRZ நிலை',
    'Wetland Status': 'ஈரநில நிலை',
    'Waterbody Status': 'நீர்வழிப்பாதை நிலை',
    'Flood Zone': 'வெள்ள மண்டலம்',
    'Protected Area': 'பாதுகாக்கப்பட்ட பகுதி',
    'Waterbody Distance': 'நீர்நிலை தூரம்',
    'Environmental Restriction': 'சுற்றுச்சூழல் கட்டுப்பாடு',
    'Land Use': 'நிலப் பயன்பாடு',
    'Zoning': 'மண்டல வகைப்பாடு',
    'Master Plan Zone': 'முக்கிய திட்ட மண்டலம்',
    'Development Zone': 'வளர்ச்சி மண்டலம்',
    'Permitted Use': 'அனுமதிக்கப்பட்ட பயன்பாடு',
    'FSI / FAR': 'FSI / FAR அளவு',
    'Maximum Building Height': 'அதிகபட்ச கட்டிட உயரம்',
    'Front Setback': 'முன் இடைவெளி',
    'Side Setback': 'பக்க இடைவெளி',
    'Planning Permission': 'திட்ட அனுமதி',
    'Proposed Land Use': 'முன்மொழியப்பட்ட பயன்பாடு',

    // Common Values
    'Active': 'செயலில்',
    'Verified': 'சரிபார்க்கப்பட்டது',
    'Completed': 'நிறைவடைந்தது',
    'Available': 'கிடைக்கக்கூடியது',
    'Approved': 'அங்கீகரிக்கப்பட்டது',
    'Paid': 'செலுத்தப்பட்டது',
    'Clear': 'தெளிவானது (வில்லங்கமற்றது)',
    'Residential': 'குடியிருப்பு',
    'Agricultural': 'விவசாயம்',
    'Individual': 'தனிநபர்',
    'None': 'இல்லை',
    'Not Required': 'தேவையில்லை',
    'Not Applicable': 'பொருந்தாது',
    'Existing': 'தற்போதுள்ளது',
    'Polygon': 'பலகோணம் (பாலிகான்)',
    'Updated': 'புதுப்பிக்கப்பட்டது'
  },
  hi: {
    'Parcel ID': 'पार्सल आईडी',
    'ULPIN': 'भू-आधार यूलपिन',
    'Patta Number': 'पट्टा संख्या',
    'Survey Number': 'सर्वेक्षण संख्या',
    'Sub-Division Number': 'उप-प्रभाग संख्या',
    'Sub-Division': 'उप-प्रभाग',
    'Owner Name': 'स्वामी का नाम',
    'Ownership Type': 'स्वामित्व प्रकार',
    'Land Area': 'भूमि क्षेत्र',
    'Parcel Area': 'पार्सल क्षेत्र',
    'Land Classification': 'भूमि वर्गीकरण',
    'Land Type': 'भूमि प्रकार',
    'Patta Status': 'पट्टा स्थिति',
    'Mutation Status': 'दाखिल-खारिज स्थिति',
    'District': 'जिला',
    'Taluk': 'तहसील / तालुका',
    'Village': 'ग्राम / गांव',
    'Parcel Boundary': 'पार्सल सीमा',
    'Boundary Status': 'सीमा स्थिति',
    'Survey Status': 'सर्वेक्षण स्थिति',
    'Cadastral Map': 'भू-कर मानचित्र',
    'FMB Sketch': 'एफएमबी स्केच',
    'Latitude': 'अक्षांश',
    'Longitude': 'देशांतर',
    'Adjacent Parcels': 'समीपवर्ती पार्सल',
    'Boundary Coordinates': 'सीमा निर्देशांक',
    'Document Number': 'दस्तावेज़ संख्या',
    'Document Type': 'दस्तावेज़ प्रकार',
    'Registration Date': 'पंजीकरण तिथि',
    'Registration Office': 'पंजीकरण कार्यालय',
    'Transaction Type': 'लेनदेन प्रकार',
    'Transferor': 'हस्तांतरणकर्ता',
    'Transferee': 'हस्तांतरिती',
    'Transaction Value': 'लेनदेन मूल्य',
    'Encumbrance Status': 'भार स्थिति',
    'Mortgage Status': 'बंधक स्थिति',
    'EC Status': 'ईसी स्थिति',
    'Document Status': 'दस्तावेज़ स्थिति',
    'Property ID': 'संपत्ति आईडी',
    'Assessment Number': 'मूल्यांकन संख्या',
    'Ward Number': 'वार्ड संख्या',
    'Local Body': 'स्थानीय निकाय',
    'Property Type': 'संपत्ति प्रकार',
    'Property Usage': 'संपत्ति उपयोग',
    'Building Status': 'भवन स्थिति',
    'Property Tax Status': 'संपत्ति कर स्थिति',
    'Tax Amount': 'कर राशि',
    'Tax Arrears': 'कर बकाया',
    'Assessment Status': 'मूल्यांकन स्थिति',
    'Road Width': 'सड़क की चौड़ाई',
    'Right of Way': 'मार्ग का अधिकार',
    'Distance from Parcel': 'पार्सल से दूरी',
    'Affected Area': 'प्रभावित क्षेत्र',
    'Acquisition Status': 'अधिग्रहण स्थिति',
    'Development Restriction': 'विकास प्रतिबंध',
    'Building Usage': 'भवन उपयोग',
    'Building Permission': 'भवन अनुमति',
    'Property Tax': 'संपत्ति कर',
    'Water Connection': 'जल संयोजन',
    'Sewerage Connection': 'सीवरेज संयोजन',
    'Agricultural Land Status': 'कृषि भूमि स्थिति',
    'Crop Type': 'फसल प्रकार',
    'Soil Type': 'मिट्टी का प्रकार',
    'Irrigation Type': 'सिंचाई प्रकार',
    'Forest Type': 'वन प्रकार',
    'Buffer Zone': 'बफर जोन',
    'Eco-Sensitive Zone': 'पर्यावरण-संवेदनशील क्षेत्र',
    'Connection ID': 'कनेक्शन आईडी',
    'Consumer ID': 'उपभोक्ता आईडी',
    'Connection Status': 'कनेक्शन स्थिति',
    'Transformer ID': 'ट्रांसफार्मर आईडी',
    'Pole ID': 'पोल आईडी',
    'Power Line': 'विद्युत लाइन',
    'Land Use': 'भूमि उपयोग',
    'Zoning': 'ज़ोनिंग',
    'Planning Permission': 'नियोजन अनुमति',

    'Active': 'सक्रिय',
    'Verified': 'सत्यापित',
    'Completed': 'पूर्ण',
    'Available': 'उपलब्ध',
    'Approved': 'स्वीकृत',
    'Paid': 'भुगतान किया',
    'Clear': 'भारमुक्त (स्पष्ट)',
    'Residential': 'आवासीय',
    'Agricultural': 'कृषि',
    'Individual': 'व्यक्तिगत',
    'None': 'कोई नहीं',
    'Not Required': 'आवश्यक नहीं'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('landstack_lang') || 'en';
  });

  const changeLanguage = (code) => {
    setCurrentLang(code);
    localStorage.setItem('landstack_lang', code);
    document.documentElement.lang = code;
  };

  const t = (key) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  // Helper to translate parameter labels and common values across languages
  const tParam = (labelOrValue) => {
    if (!labelOrValue) return labelOrValue;
    const str = String(labelOrValue).trim();
    if (PARAM_TRANSLATIONS[currentLang] && PARAM_TRANSLATIONS[currentLang][str]) {
      return PARAM_TRANSLATIONS[currentLang][str];
    }
    return labelOrValue;
  };

  const currentLangObj = INDIAN_LANGUAGES.find(l => l.code === currentLang) || INDIAN_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ currentLang, currentLangObj, changeLanguage, t, tParam, languages: INDIAN_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
